// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAixVYxUX3ycVye6UNaS2GYFaek9GlTJMQ',
    appId: '1:536090020293:web:89bd86cb4c3c14129963ac',
    messagingSenderId: '536090020293',
    projectId: 'presintation-2530e',
    authDomain: 'presintation-2530e.firebaseapp.com',
    databaseURL: 'https://presintation-2530e-default-rtdb.firebaseio.com',
    storageBucket: 'presintation-2530e.appspot.com',
    measurementId: 'G-ZWDLQHJE4G',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC_lqwTIaPflwx-YCFYX-B4Ne0B0e-8rf0',
    appId: '1:536090020293:android:26ef17c2a6102b7d9963ac',
    messagingSenderId: '536090020293',
    projectId: 'presintation-2530e',
    databaseURL: 'https://presintation-2530e-default-rtdb.firebaseio.com',
    storageBucket: 'presintation-2530e.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA2xAdzl2DY91UtVfNBVXfoJ6XF-BFFtlA',
    appId: '1:536090020293:ios:11b838b10c3ac8939963ac',
    messagingSenderId: '536090020293',
    projectId: 'presintation-2530e',
    databaseURL: 'https://presintation-2530e-default-rtdb.firebaseio.com',
    storageBucket: 'presintation-2530e.appspot.com',
    iosClientId: '536090020293-v9fh8cr1bov91bdkk9tof8ebq6khk21k.apps.googleusercontent.com',
    iosBundleId: 'com.example.presintation',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA2xAdzl2DY91UtVfNBVXfoJ6XF-BFFtlA',
    appId: '1:536090020293:ios:11b838b10c3ac8939963ac',
    messagingSenderId: '536090020293',
    projectId: 'presintation-2530e',
    databaseURL: 'https://presintation-2530e-default-rtdb.firebaseio.com',
    storageBucket: 'presintation-2530e.appspot.com',
    iosClientId: '536090020293-v9fh8cr1bov91bdkk9tof8ebq6khk21k.apps.googleusercontent.com',
    iosBundleId: 'com.example.presintation',
  );
}
